#  Webscraping avec python
# **Python**
# **TP 6 - Scraping avec BeautifulSoup**

**Inspiré de : [Cours de Python pour le Data Scientist - Lino Galiana](https://linogaliana-teaching.netlify.app/manipulation/webscraping/)**


***

[**Notions**](#notions)

1. [Balises HTML](#1)
2. [Parent et enfant](#2)
3. [Utiliser BeautifulSoup](#3)


*** 

[**Exercices**](#exercices)

- Exercice 1
- Exercice 2

***

<a id='1'></a>

## 1. Balises HTML


En HTML, on utilise des balises pour séparer les différents morceaux du code qui correspondent à des éléments sur la page. Par exemple ``<head>`` est la balise pour le header du fichier html, ``<title>`` pour son titre, ``<p>`` pour un pragraphe, ``<h1>``, ``<h2>``, ``<h3>``,... pour des headlines ou ``<br>``pour un retour à la ligne.


Une balise est toujours fermée par la même balise avec un ``/``en plus. Par exemple : ``<title> Titre </title>``

#### Exemple : les balise des tableaux

$$
\begin{array}{rr} \hline
Balise  & \text{Description} \\ \hline
< table> & \text{Tableau} \\
< caption>& \text{Titre du tableau} \\
< tr> & \text{Ligne de tableau} \\
< th> & \text{Cellule d'en-tête}\\
< td> & \text{Cellule} \\
< thead> & \text{Section de l'en-tête du tableau} \\
< tbody> & \text{Section du corps du tableau} \\
< tfoot> & \text{Section du pied du tableau} \\
\end{array}
$$

##### Application : un tableau en HTML

Le code *HTML* du tableau suivant

<table>
<caption> Le Titre de mon tableau </caption>
    <thead>
       <tr>
          <th>Prénom</th>
          <th>Nom</th>
          <th>Profession</th>
       </tr>
   </thead>
   <tbody>
       <tr>
          <td>Mike </td>
          <td>Stuntman</td>
          <td>Cascadeur</td>
       </tr>
       <tr>
          <td>Mister</td>
          <td>Pink</td>
          <td>Gangster</td>
       </tr>
   </tbody>
</table>

Donnera dans le navigateur

<table>
<caption> Le Titre de mon tableau </caption>

   <tr>
      <th>Prénom</th>
      <th>Nom</th>
      <th>Profession</th>
   </tr>
   <tr>
      <td>Mike </td>
      <td>Stuntman</td>
      <td>Cascadeur</td>
   </tr>
   <tr>
      <td>Mister</td>
      <td>Pink</td>
      <td>Gangster</td>
   </tr>
</table>

<a id='2'></a>
## 2. Parent et enfant

Dans le cadre du langage HTML, les termes de parents (parent) et enfants (child) servent à désigner des élements emboîtés les uns dans les autres. Dans la construction suivante, par exemple :

<div> 
    <p>
       bla,bla
    </p>
</div>




<div>
    <div> 
    
    </div>
    
    <p>
       bla,bla
    </p>
</div>

Sur la page web, cela apparaitra de la manière suivante : 

<div> 
    <p>
       bla,bla
    </p>
</div>

On dira que l'élément ``<div>`` est le parent de l'élément ``<p>`` tandis que l'élément ``<p>`` est l'enfant de l'élément ``<div>``.

## 3. Utiliser BeautifulSoup

Les packages et étapes pour scrapper des pages HTML : 
- Etape 1: ``requests`` ou ``urllib`` pour faire des requêtes `GET` sur les pages
- Etape 2: ``BeautifulSoup4`` pour parser le code HTML

In [1]:
import urllib
import bs4
import requests

### 1ere page HTML

On va commencer facilement, prenons une page wikipedia, par exemple celle de la Ligue 1 de football : [Championnat de France de football 2019-2020](https://fr.wikipedia.org/wiki/Championnat_de_France_de_football_2019-2020). On va souhaiter récupérer la liste des équipes, ainsi que les url des pages Wikipedia de ces équipes.

In [2]:
# Etape 1 : se connecter à la page wikipedia et obtenir le code source

url_ligue_1 = "https://fr.wikipedia.org/wiki/Championnat_de_France_de_football_2019-2020"
    
#from urllib import request
# Je rajoute un headers de requête.
# Pour éviter d'avoir un code 403
# "on trompe le serveur"
headers = {
    "User-Agent": "unnomlambda/1.0 (shikamaru--@hotmail.fr)"
}

response = requests.get(url_ligue_1, headers=headers)
print(f"Status code: {response.status_code}")

print(response.headers["content-type"])
text = response.text
#print(request_text[:1000])    
#print("\n type:", type(request_text))


# Etape 2 : utiliser le package BeautifulSoup
page = bs4.BeautifulSoup(text, "html")

print(type(page))
print(text[:100])

Status code: 200
text/html; charset=UTF-8
<class 'bs4.BeautifulSoup'>
<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-la

### Méthode ``.find()``
Elle renvoie la première occurence trouvée avec cette balise

In [3]:
title = page.find("title")

print(title)
print(type(title))
print("\n")

print(title.text)
print(type(title.text))

#print(type(page.find("title")))

<title>Championnat de France de football 2019-2020 — Wikipédia</title>
<class 'bs4.element.Tag'>


Championnat de France de football 2019-2020 — Wikipédia
<class 'str'>

In [4]:
# print(page.find("table"))

La cellule avec le copier-coller du code source donne : 

<table><caption style="background:#99cc99;color:#000000;">Généralités</caption><tbody><tr>
<th scope="row" style="width:10.5em;">Sport</th>
<td>
<a href="/wiki/Football" title="Football">Football</a></td>
</tr>
<tr>
<th scope="row" style="width:10.5em;">Organisateur(s)</th>
<td>
<a href="/wiki/Ligue_de_football_professionnel" title="Ligue de football professionnel">LFP</a></td>
</tr>
<tr>
<th scope="row" style="width:10.5em;">Édition</th>
<td>
<abbr class="abbr" title="Quatre-vingt-deuxième (huitante-deuxième / octante-deuxième)">82<sup>e</sup></abbr></td>
</tr>
<tr>
<th scope="row" style="width:10.5em;">Lieu(x)</th>
<td>
<span class="datasortkey" data-sort-value="France"><span class="flagicon"><a class="image" href="/wiki/Fichier:Flag_of_France.svg" title="Drapeau de la France"><img alt="Drapeau de la France" class="noviewer thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/20px-Flag_of_France.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/30px-Flag_of_France.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/40px-Flag_of_France.svg.png 2x" width="20"/></a> </span><a href="/wiki/France" title="France">France</a></span> et <br/><span class="datasortkey" data-sort-value="Monaco"><span class="flagicon"><a class="image" href="/wiki/Fichier:Flag_of_Monaco.svg" title="Drapeau de Monaco"><img alt="Drapeau de Monaco" class="noviewer thumbborder" data-file-height="800" data-file-width="1000" decoding="async" height="16" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/20px-Flag_of_Monaco.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/30px-Flag_of_Monaco.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/40px-Flag_of_Monaco.svg.png 2x" width="20"/></a> </span><a href="/wiki/Monaco" title="Monaco">Monaco</a></span></td>
</tr>
<tr>
<th scope="row" style="width:10.5em;">Date</th>
<td>
Du <time class="nowrap date-lien" data-sort-value="2019-08-09" datetime="2019-08-09"><a href="/wiki/9_ao%C3%BBt_en_sport" title="9 août en sport">9</a> <a class="mw-redirect" href="/wiki/Ao%C3%BBt_2019_en_sport" title="Août 2019 en sport">août</a> <a href="/wiki/2019_en_football" title="2019 en football">2019</a></time><br/>au <time class="nowrap date-lien" data-sort-value="2020-03-08" datetime="2020-03-08"><a href="/wiki/8_mars_en_sport" title="8 mars en sport">8 mars</a> <a href="/wiki/2020_en_football" title="2020 en football">2020</a></time> <small>(arrêt définitif)</small></td>
</tr>
<tr>
<th scope="row" style="width:10.5em;">Participants</th>
<td>
20 équipes</td>
</tr>
<tr>
<th scope="row" style="width:10.5em;">Matchs joués</th>
<td>
279</td>
</tr>
<tr>
<th scope="row" style="width:10.5em;">Site web officiel</th>
<td>
<a class="external text" href="https://www.ligue1.fr/" rel="nofollow">Site officiel</a></td>
</tr></tbody></table>

### Méthode ``.find_all()``
Elle renvoie toutes les occurences trouvées avec cette balise

In [5]:
all_tables = page.find_all("table")
print("Il y a", len(all_tables), "éléments dans la page qui sont des <table>")

print(type(all_tables)) # ResultSet : fonctionne comme une liste
print(type(all_tables[0]))

# all_tables[12]

Il y a 34 éléments dans la page qui sont des <table>
<class 'bs4.element.ResultSet'>
<class 'bs4.element.Tag'>

### Attribut ``.text``
Il contient le texte entre des bablises

In [6]:
paragraph = page.find_all("p")[10]
print(paragraph)
print(paragraph.text)

<p>Le classement est calculé avec le barème de points suivant : une victoire vaut trois points, le match nul un. La défaite ne rapporte aucun point.
</p>
Le classement est calculé avec le barème de points suivant : une victoire vaut trois points, le match nul un. La défaite ne rapporte aucun point.

### Filtrer sur une classe HTML avec ``find``ou ``find_all``

In [7]:
wikitables = page.find_all("table", class_='wikitable sortable')
print(len(wikitables), "objects with class wikitable sortable")

2 objects with class wikitable sortable

### ``.get``pour récupérer un attribut
Ici, on récupère l'attribut ``href``d'un tag avec ``.get("href")``

In [8]:
wikitables[0].find_all("th")[3]

<th scope="col">Classement<br/><a href="/wiki/Championnat_de_France_de_football_2018-2019" title="Championnat de France de football 2018-2019">2018-2019</a>
</th>

In [9]:
wikitables = page.find_all("table", class_='wikitable sortable')
print(len(wikitables), "objects with class wikitable sortable")

# th indique la ligne d'entête du tableau, on prend la troisième cellule 
# de la liste des entêtes
tag_header = wikitables[0].find_all("th")[3]
print(tag_header)
print('\n')

# on cherche maintenant la balise a dedans
tag_a = tag_header.find("a")
print(tag_a)
print(tag_a.get("href"))

2 objects with class wikitable sortable
<th scope="col">Classement<br/><a href="/wiki/Championnat_de_France_de_football_2018-2019" title="Championnat de France de football 2018-2019">2018-2019</a>
</th>


<a href="/wiki/Championnat_de_France_de_football_2018-2019" title="Championnat de France de football 2018-2019">2018-2019</a>
/wiki/Championnat_de_France_de_football_2018-2019

In [10]:
# première table
# 4ème header
# l'unique lien qui se trouve dedans (d'où l'usage)
# récupération de l'url relative

page.find_all("table", class_='wikitable sortable')[0].find_all("th")[3].find("a").get("href")

'/wiki/Championnat_de_France_de_football_2018-2019'

## Exercices

## Exercice 1 : obtenir la liste des équipes de Ligue 1

Sur la page https://fr.wikipedia.org/wiki/Championnat_de_France_de_football_2019-2020, on veut scraper le tableau de la section Participants (celui avec ces colonnes : (Club, Dernière montée, Budget en M€, ...)

#### 1) Trouver le tableau

In [11]:
import urllib
import bs4
import requests

# A toi de jouer
url="https://fr.wikipedia.org/wiki/Championnat_de_France_de_football_2019-2020"
headers = {
    "User-Agent": "unnomlambda/1.0 (shikamaru--@hotmail.fr)"
}

response = requests.get(url, headers=headers)
print(f"Status code: {response.status_code}")

wikitables = page.find_all("table", class_='wikitable sortable')
print(f"il y a: {len(wikitables)} tables")

#vérifier le tableau qu'on a besoin :
for x, table in enumerate (wikitables):
   if "Dernière" "montée" in table.text:
       print("index:", x)

Status code: 200
il y a: 2 tables
index: 0

#### 2) Récupérer chaque ligne du table

In [12]:
# A toi de jouer
#Extraire les en-têtes (th)
tete_html = wikitables[0].find_all("th")

tete = []
for th in tete_html:
     tete.append(th.text.rstrip("\n"))
tete

#Extraire les lines:
# On ignore la première ligne (les en-têtes déjà récupérés)
lines_html =wikitables[0].find_all("tr")
lines = []
for tr in lines_html[1:]:
    line = []
    tds = tr.find_all("td")
    for td in tds:
        line.append(td.text.rstrip("\n"))
    lines.append(line)

lines

import pandas as pd

df = pd.DataFrame(lines, columns= tete)
df

#for i , element in enumerate(lines):
#    print(f"lines{i}: ", element,"\n")

,Club,Dernièremontée,Budget[3]en M€,Classement2018-2019,Entraîneur,Depuis,Stade,Capacitéen L1[4],Nombrede saisonsen L1
0,Paris Saint-Germain,1974,637,1er,Thomas Tuchel,2018,Parc des Princes,47 929,46
1,LOSC Lille,2000,120,2e,Christophe Galtier,2017,Stade Pierre-Mauroy,49 712,59
2,Olympique lyonnais,1989,310,3e,Rudi Garcia,2019,Groupama Stadium,57 206,60
3,AS Saint-Étienne,2004,100,4e,Claude Puel,2019,Stade Geoffroy-Guichard,41 965,66
4,Olympique de Marseille,1996,110,5e,André Villas-Boas,2019,Orange Vélodrome,66 226,69
5,Montpellier HSC,2009,40,6e,Michel Der Zakarian,2017,Stade de la Mosson,22 000,27
6,OGC Nice,2002,50,7e,Patrick Vieira,2018,Allianz Riviera,35 596,60
7,Stade de Reims,2018,45,8e,David Guion,2017,Stade Auguste-Delaune,20 546,35
8,Nîmes Olympique,2018,27,9e,Bernard Blaquart,2015,Stade des Costières,15 788,35
9,Stade rennais FC,1994,65,10e,Julien Stéphan,2018,Roazhon Park,29 194,62
10,RC Strasbourg Alsace,2017,43,11e,Thierry Laurey,2016,Stade de la Meinau,26 109,58
11,FC Nantes,2013,70,12e,Christian Gourcuff,2019,Stade de la Beaujoire - Louis Fonteneau,35 322,51
12,SCO d’Angers,2015,32,13e,Stéphane Moulin,2011,Stade Raymond-Kopa,14 582,27
13,Girondins de Bordeaux,1992,70,14e,Paulo Sousa,2019,Matmut Atlantique,42 115,66
14,Amiens SC,2017,30,15e,Luka Elsner,2019,Stade Crédit Agricole la Licorne,12 999,2
15,Toulouse FC,2003,35,16e,Denis Zanko,2020,Stadium de Toulouse,33 033,32
16,AS Monaco,2013,220,17e,Robert Moreno,2019,Stade Louis-II,16 500,60
17,Dijon FCO,2016,38,18e,Stéphane Jobard,2019,Parc des Sports Gaston-Gérard,15 459,4
18,FC Metz,2019,40,1er (Ligue 2),Vincent Hognon,2019,Stade Saint-Symphorien,25 865,61
19,Stade brestois 29,2019,30,2e (Ligue 2),Olivier Dall'Oglio,2019,Stade Francis-Le Blé,14 920,13

## Exercice 2
- A partir de la suivante : [pokedex](https://pokemondb.net/pokedex/national), l'objectif est de constituer la liste de tous les pokemons
 - 1. Dans un premier temps, on voudrait la liste avec nom, numéro et types pour chaque pokémon
 - 2. Ensuite, on souhaiterait aussi garder l'url pour chaque pokemon (par exemple en utilisant l'attribut ``href``) pour pouvoir ensuite faire une requête ``GET``sur cette page (par exemple : https://pokemondb.net/pokedex/venusaur) et récupérer les données de taille et de poids

In [13]:
# A toi de jouer
import urllib
import bs4
import requests

url_pokedex = "https://pokemondb.net/pokedex/national"
headers = {
    "User-Agent": "unnomlambda/1.0 (shikamaru--@hotmail.fr)"
}

response = requests.get(url_pokedex, headers=headers)
print(f"Status code: {response.status_code}")

Status code: 200

In [14]:
HOST_URL = "https://pokemondb.net"


text = response.text
# Etape 2 : utiliser le package BeautifulSoup
page = bs4.BeautifulSoup(text, "html")

pokemons= []
cards = page.find_all("div", class_ = "infocard")
for card in cards:
      # Numéro
    numero = card.find("small").text.lstrip("#")
    # Nom et URL
    link = card.find("a", class_ = "ent-name")
    nom = link.text
    url_poke = link.get("href")
   
    #type:
    types = [t.text for t in card.find_all("a", class_ = "itype")]
   
    pokemon = {
        "Numéro ": numero,
        "Name": nom,
        "Type":" ".join(types),    
        "url":HOST_URL + url_poke
    }
    pokemons.append(pokemon)

In [15]:
df = pd.DataFrame(pokemons)
print(f"Liste initiale de {len(df)} Pokémon extraite.")
df

Liste initiale de 1025 Pokémon extraite.

,Numéro,Name,Type,url
0,0001,Bulbasaur,Grass Poison,https://pokemondb.net/pokedex/bulbasaur
1,0002,Ivysaur,Grass Poison,https://pokemondb.net/pokedex/ivysaur
2,0003,Venusaur,Grass Poison,https://pokemondb.net/pokedex/venusaur
3,0004,Charmander,Fire,https://pokemondb.net/pokedex/charmander
4,0005,Charmeleon,Fire,https://pokemondb.net/pokedex/charmeleon
...,...,...,...,...
1020,1021,Raging Bolt,Electric Dragon,https://pokemondb.net/pokedex/raging-bolt
1021,1022,Iron Boulder,Rock Psychic,https://pokemondb.net/pokedex/iron-boulder
1022,1023,Iron Crown,Steel Psychic,https://pokemondb.net/pokedex/iron-crown
1023,1024,Terapagos,Normal,https://pokemondb.net/pokedex/terapagos
1024,1025,Pecharunt,Poison Ghost,https://pokemondb.net/pokedex/pecharunt

In [16]:
#j'ai récupérer tous les liens de ppokemons
liens = []
tailles = []
poids = []
for pokemon in pokemons:
    lien = pokemon["url"]
    headers = {
    "User-Agent": "unnomlambda/1.0 (shikamaru--@hotmail.fr)"
    }
    rep = requests.get(lien, headers=headers)
    liens.append(lien)
#for l in liens: print(l) /afficher tous les liens 
    soup_poke = bs4.BeautifulSoup(rep.text, "html")
    vitals = soup_poke.find("table", {"class": "vitals-table"})

# Extraction du texte brut
    h_text = vitals.find("th", string="Height").find_next_sibling("td").text
    w_text = vitals.find("th", string="Weight").find_next_sibling("td").text
        
# Nettoyage pour ne garder que la valeur (ex: 0.7)
    h_clean = h_text.split("m")[0].strip()
    w_clean = w_text.split("kg")[0].strip()
        
    tailles.append(h_clean)
    poids.append(w_clean)

In [17]:
# 3. Ajout au DataFrame final
df["Taille (m)"] = tailles
df["Poids (kg)"] = poids


# Affiche les 10 premières lignes pour vérifier que Taille et Poids sont bien là
print(df.head(10))

  Numéro         Name          Type                                       url  \
0    0001   Bulbasaur  Grass Poison   https://pokemondb.net/pokedex/bulbasaur
1    0002     Ivysaur  Grass Poison     https://pokemondb.net/pokedex/ivysaur
2    0003    Venusaur  Grass Poison    https://pokemondb.net/pokedex/venusaur
3    0004  Charmander          Fire  https://pokemondb.net/pokedex/charmander
4    0005  Charmeleon          Fire  https://pokemondb.net/pokedex/charmeleon
5    0006   Charizard   Fire Flying   https://pokemondb.net/pokedex/charizard
6    0007    Squirtle         Water    https://pokemondb.net/pokedex/squirtle
7    0008   Wartortle         Water   https://pokemondb.net/pokedex/wartortle
8    0009   Blastoise         Water   https://pokemondb.net/pokedex/blastoise
9    0010    Caterpie           Bug    https://pokemondb.net/pokedex/caterpie

  Taille (m) Poids (kg)
0        0.7        6.9
1        1.0       13.0
2        2.0      100.0
3        0.6        8.5
4        1.1       19.0
5        1.7       90.5
6        0.5        9.0
7        1.0       22.5
8        1.6       85.5
9        0.3        2.9